"""add audit_logs feedback carer_proxies tables

Revision ID: bb5c1bb3bb30
Revises: 1118ff937eaf
Create Date: 2026-06-08 13:55:32.113895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb5c1bb3bb30'
down_revision = '1118ff937eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carer_proxies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('staff_user_id', sa.String(length=36), nullable=False),
    sa.Column('carer_name', sa.String(length=100), nullable=False),
    sa.Column('carer_relationship', sa.String(length=50), nullable=False),
    sa.Column('carer_contact', sa.String(length=120), nullable=True),
    sa.Column('patient_identifier', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['staff_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('prediction_risk_tier', sa.String(length=20), nullable=False),
    sa.Column('prediction_probability', sa.Float(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_table('carer_proxies')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
